### PR TITLE
Update to es6

### PR DESCRIPTION
**Pull request by richyliu**
replace var with let
replace for loops with for of (where appropriate)
replace function() {} with () => {}

### CODE REVIEW

**Comment by jeffreymeng** [comment]
tsk tsk
https://hacktoberfestchecker.herokuapp.com/
Jonathan probably isn't going to accept(or view) this any time soon, so you might as well just do it yourself.

**Comment by richyliu** [comment]
I'm trying to get 4 pr's for hackotober

**Comment by jeffreymeng** [comment]
obviously

**Comment by jeffreymeng** [comment]
good news: you're there https://hacktoberfestchecker.herokuapp.com/?username=richyliu

**Pull request merged**
